import Image from "next/image";
import { ContactForm, ReservationForm } from "./contact-form";

const services = [
  { number: "01", eyebrow: "Étterem", title: "Kulináris pillanatok: dőljön hátra, a többit bízza ránk.", text: "Várjuk egy kötetlen családi ebédre, egy fontos üzleti találkozóra vagy egy meghitt, kettesben eltöltött vacsorára. Válasszon gondosan összeállított étlapunkról, adja át magát a nyugalomnak, mi pedig gondoskodunk a tökéletes vendégélményről.", cta: "Felfedezem az éttermet", href: "#etlap" },
  { number: "02", eyebrow: "Közétkeztetés", title: "Kiszámítható minőség, kompromisszumok nélkül.", text: "Intézmények és szervezetek számára nyújtunk megbízható és magas színvonalú étkezési megoldásokat. Jól szervezett hátterünkkel alkalmazkodunk partnereink egyedi igényeihez.", cta: "Közétkeztetés részletei", href: "#erdeklodes" },
  { number: "03", eyebrow: "Rendezvények", title: "Mérföldkövek méltó környezetben, szervezési terhek nélkül.", text: "Születésnap, évforduló, ballagás, osztálytalálkozó vagy céges vacsora? A menüt és a vendéglátást az esemény jellegéhez igazítjuk, hogy Önnek és vendégeinek csak az élmény maradjon.", cta: "Rendezvényt tervezek", href: "#erdeklodes" },
  { number: "04", eyebrow: "Catering", title: "A Kastélydomb minősége az Ön által választott helyszínen.", text: "Professzionális catering szolgáltatásunkkal külső helyszínekre is elvisszük a tőlünk megszokott minőséget és figyelmes szervizt, legyen szó elegáns állófogadásról vagy családi rendezvényről.", cta: "Catering ajánlatot kérek", href: "#erdeklodes" },
  { number: "05", eyebrow: "Esküvő", title: "Az Önök nagy napja, a mi évtizedes szakértelmünk.", text: "Az esküvői vendéglátás megtervezésétől a hajnalig tartó profi kiszolgálásig ott állunk Önök mellett. Helyszínünket és menüinket úgy alakítjuk, hogy ez a nap valóban csak Önökről szóljon.", cta: "Esküvőt tervezünk", href: "#erdeklodes" },
];

function BrandMark({ inverse = false }: { inverse?: boolean }) {
  return <span className={`brand-mark ${inverse ? "brand-mark--inverse" : ""}`} aria-hidden="true"><svg viewBox="0 0 64 64" role="img"><circle cx="32" cy="32" r="31" fill="#d7b45a" /><path d="M11 43C22 37 33 30 41 5h17v19C43 26 32 35 24 55H11V43Z" fill="#ba2934" /><path d="M17 49c10-2 17-1 23 2M21 46c7-9 13-19 17-34M16 39c9-4 16-9 22-17" fill="none" stroke="#fff" strokeWidth="4.2" strokeLinecap="round" /></svg></span>;
}

function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  return (
    <main id="top">
      <div className="announcement"><div className="shell announcement__inner"><span>Várpalota · Kastélydomb</span><a href="tel:+36302644081">Asztalfoglalás: +36 30 264 4081</a></div></div>
      <header className="site-header"><div className="shell header__inner">
        <a className="brand" href="#top" aria-label="Kastélydomb Kávézó és Étterem – kezdőlap"><BrandMark /><span className="brand__word"><b>kastélydomb</b><small>Kávézó és Étterem</small></span></a>
        <nav className="desktop-nav" aria-label="Fő navigáció"><a href="#rolunk">Rólunk</a><a href="#etlap">Étlap</a><a href="#szolgaltatasok">Szolgáltatások</a><a href="#kapcsolat">Kapcsolat</a></nav>
        <a className="header-cta" href="#foglalas">Asztalfoglalás <Arrow /></a>
        <details className="mobile-nav"><summary aria-label="Menü megnyitása"><span /><span /></summary><nav aria-label="Mobil navigáció"><a href="#rolunk">Rólunk</a><a href="#etlap">Étlap</a><a href="#szolgaltatasok">Szolgáltatások</a><a href="#kapcsolat">Kapcsolat</a><a href="#foglalas">Asztalfoglalás</a></nav></details>
      </div></header>

      <section className="hero" aria-labelledby="hero-title">
        <div className="hero__slides" aria-hidden="true"><Image className="hero__slide hero__slide--one" src="/images/etterem-belso.webp" alt="" fill priority sizes="100vw" /><Image className="hero__slide hero__slide--two" src="/images/etterem-03.webp" alt="" fill sizes="100vw" /><Image className="hero__slide hero__slide--three" src="/images/etterem-08.webp" alt="" fill sizes="100vw" /></div><div className="hero__veil" />
        <div className="shell hero__inner"><p className="kicker kicker--light">Étterem · Rendezvények · Catering · Esküvők</p><h1 id="hero-title">Ahol az ízekből emlékek, a találkozásokból <em>ünnepek lesznek.</em></h1><p className="hero__lead">Várpalota szívében időt és teret adunk a legfontosabb pillanatoknak. Több évtizedes tapasztalattal gondoskodunk arról, hogy Önnek csak egyetlen dolga legyen: megélni a pillanatot.</p><div className="button-row"><a className="button button--gold" href="#foglalas">Asztalfoglalás <Arrow /></a><a className="button button--ghost" href="#etlap">Étlap megtekintése <span aria-hidden="true">↓</span></a></div></div>
        <div className="hero__place"><span>47° 11&apos; N</span><b>Várpalota · Kastélydomb</b></div><a className="hero__scroll" href="#rolunk" aria-label="Tovább a Rólunk szakaszhoz"><span>Görgessen</span><i /></a>
      </section>

      <section className="about section" id="rolunk"><div className="shell about__grid">
        <div className="about__copy"><p className="section-label">01 · A mi történetünk — Kastélydomb</p><h2>Több mint egy szépen terített asztal: <em>egy élmény, amelyet magával visz.</em></h2><div className="about__body"><p className="lead-copy">A Kastélydomb páratlan atmoszférájában olyan teret álmodtunk meg, ahol az időt egy kicsit másképp mérik.</p><p>Több mint 30 évnyi vendéglátói tapasztalattal pontosan tudjuk, hogy a valódi minőség nem csupán a tányérra kerülő ételeket jelenti. Sokkal inkább az apró részletek harmóniáját, az értő figyelmet és azt a megismételhetetlen érzést, amellyel a nap végén távozik tőlünk.</p><p>Legyen szó könnyed ebédről, meghitt vacsoráról vagy a család legfontosabb ünnepeiről, nálunk minden alkalom személyre szabott gondoskodást kap.</p></div></div>
        <div className="about__visual"><div className="about__image about__image--main"><Image src="/images/etterem-belso.webp" alt="A Kastélydomb Kávézó és Étterem belső tere" fill sizes="(max-width: 900px) 90vw, 42vw" /></div><div className="about__image about__image--detail"><Image src="/images/etterem-03.webp" alt="Elegáns teríték a Kastélydomb éttermében" fill sizes="(max-width: 900px) 48vw, 19vw" /></div><div className="experience"><strong>30+</strong><span>év vendéglátói<br />tapasztalat</span></div></div>
      </div><div className="shell highlights" aria-label="Kiemelt szolgáltatások"><div><span>01</span><b>Várpalota</b><p>Könnyen elérhető helyszín a Kastélydombon.</p></div><div><span>02</span><b>À la carte</b><p>Minőségi fogások és közös étkezések.</p></div><div><span>03</span><b>Rendezvények</b><p>Családi, céges és esküvői események.</p></div><div><span>04</span><b>Catering</b><p>Vendéglátás külső helyszíneken is.</p></div></div></section>

      <section className="menu section" id="etlap"><div className="menu__backdrop"><Image src="/images/wolt-borito.webp" alt="A Kastélydomb étterem fogásai" fill sizes="100vw" /></div><div className="menu__shade" /><div className="shell menu__inner"><div className="menu__card"><p className="section-label section-label--gold">02 · Kulináris kínálatunk</p><h2>Őszinte ízek, mesteri harmónia: <em>a tányérra álmodott gondoskodás.</em></h2><p className="lead-copy">A kiváló alapanyagok és az értő elkészítés találkozása.</p><p>Étlapunkon a hagyományos, jól ismert ízek és a modern gasztronómia találkozik. Akár könnyed családi ebédre, akár ráérős, ünnepi vacsorára érkezik, nálunk azok a tartalmas fogások várják, amelyekért érdemes asztalhoz ülni. Az élményt gondosan válogatott ital- és borkínálatunk teszi teljessé.</p><div className="button-row"><a className="button button--gold" href="https://kastelydombkavezo.hu/etlap/" target="_blank" rel="noreferrer">Étlap megtekintése <Arrow /></a><a className="button button--ghost" href="https://kastelydombkavezo.hu/etteremrol/italok/" target="_blank" rel="noreferrer">Itallap megtekintése <Arrow /></a></div></div></div></section>

      <section className="services section" id="szolgaltatasok"><div className="shell"><div className="section-heading"><div><p className="section-label">03 · Több mint egy étterem</p><h2>Személyre szabott vendéglátás, <em>életének minden pillanatához.</em></h2></div><p>A hétköznapi vacsorától a megbízható közétkeztetésen és külső helyszínes cateringen át életük legfontosabb napjáig minden alkalomhoz biztos hátteret teremtünk.</p></div><div className="services__grid">{services.map((service) => <article className="service-card" key={service.number}><div className="service-card__top"><span>{service.number}</span><small>{service.eyebrow}</small></div><div><h3>{service.title}</h3><p>{service.text}</p></div><a href={service.href}>{service.cta} <Arrow /></a></article>)}</div><p className="services__note">Az egyes szolgáltatások részletes, önálló oldalai a következő fejlesztési ütemben készülnek el.</p></div></section>

      <section className="booking-callout"><div className="booking-callout__image"><Image src="/images/etterem-08.webp" alt="Ünnepi teríték a Kastélydomb rendezvénytermében" fill sizes="100vw" /></div><div className="booking-callout__shade" /><div className="shell booking-callout__content"><p className="kicker kicker--light">Egy asztal. Egy alkalom. Egy emlék.</p><h2>Már tudja, <em>mikor jönnének?</em></h2><p>Egy közös ebéd, különleges vacsora vagy nagyobb családi alkalom előtt érdemes időben lefoglalni az asztalt.</p><div className="button-row"><a className="button button--gold" href="#foglalas">Asztalfoglalás <Arrow /></a><a className="phone-link" href="tel:+36302644081">+36 30 264 4081</a></div></div></section>

      <section className="contact section" id="kapcsolat"><div className="shell"><div className="section-heading contact__heading"><div><p className="section-label">04 · Kapcsolat</p><h2>Találkozzunk <em>a Kastélydombon.</em></h2></div><p>Asztalt foglalna, rendezvényt szervez vagy valamelyik szolgáltatásunkkal kapcsolatban kérdése van? Írjon nekünk, vagy keressen elérhetőségeink egyikén.</p></div><div className="contact__layout">
        <aside className="contact-card"><div><span>Cím</span><strong>Kastélydomb Kávézó és Étterem</strong><p>8100 Várpalota, Mandulás ltp.</p></div><div><span>Telefon</span><a href="tel:+3688470350">+36 88 470 350</a><a href="tel:+36302644081">+36 30 264 4081</a></div><div><span>E-mail</span><a href="mailto:fenyocsaba@gmail.com">fenyocsaba@gmail.com</a></div><div><span>Nyitvatartás</span><p>Hétfő–csütörtök: 10:00–16:00<br />Péntek–szombat: 10:00–22:00<br />Vasárnap: 10:00–20:00</p></div><div><span>Érkezés</span><p>A vendégek számára parkolási lehetőség áll rendelkezésre.</p></div><a className="social-link" href="https://www.facebook.com/Kastelydombkavezo" target="_blank" rel="noreferrer">Facebook oldal <Arrow /></a></aside>
        <div className="form-stack"><div className="form-panel" id="foglalas"><p className="form-panel__eyebrow">Asztalfoglalás</p><h3>Foglaljon asztalt</h3><p>Adja meg az alapadatokat, és küldje el foglalási igényét.</p><ReservationForm /></div><div className="form-panel form-panel--dark" id="erdeklodes"><p className="form-panel__eyebrow">Általános kapcsolatfelvétel</p><h3>Miben segíthetünk?</h3><p>Rendezvény, közétkeztetés, catering vagy esküvő? Írja meg röviden elképzeléseit.</p><ContactForm /></div></div>
      </div></div></section>

      <footer className="footer"><div className="shell footer__main"><div className="footer__brand"><a className="brand brand--footer" href="#top"><BrandMark inverse /><span className="brand__word"><b>kastélydomb</b><small>Kávézó és Étterem</small></span></a><p>Étterem · Rendezvények · Catering · Esküvők</p></div><div><h3>Gyorslinkek</h3><a href="#rolunk">Rólunk</a><a href="#etlap">Étlap</a><a href="#szolgaltatasok">Szolgáltatások</a><a href="#foglalas">Asztalfoglalás</a></div><div><h3>Kapcsolat</h3><a href="tel:+36302644081">+36 30 264 4081</a><a href="mailto:fenyocsaba@gmail.com">fenyocsaba@gmail.com</a><p>8100 Várpalota, Mandulás</p></div><div><h3>Kövessen minket</h3><a href="https://www.facebook.com/Kastelydombkavezo" target="_blank" rel="noreferrer">Facebook <Arrow /></a><span className="muted-link">Instagram · hamarosan</span></div></div><div className="shell footer__bottom"><span>© 2026 Kastélydomb Kávézó és Étterem</span><div><span>Impresszum · előkészítés alatt</span><span>Adatkezelés · előkészítés alatt</span><a href="#top">Vissza az oldal tetejére ↑</a></div></div></footer>
    </main>
  );
}
