import Image from "next/image";
import { ContactForm } from "./contact-form";

const services = [
  { number: "01", title: "À la carte étterem", text: "Magyaros kedvencek, pizzák és frissen készülő fogások egy nyugodt ebédhez vagy ráérős vacsorához.", cta: "Megnézem az étlapot" },
  { number: "02", title: "Közétkeztetés", text: "Kiszámítható, változatos étkezési megoldás intézményeknek és közösségeknek, megbízható háttérrel.", cta: "Ajánlatot kérek" },
  { number: "03", title: "Családi és céges események", text: "Születésnap, évforduló, osztálytalálkozó vagy céges vacsora: a menütől a kiszolgálásig összefogjuk az alkalmat.", cta: "Eseményt tervezek" },
  { number: "04", title: "Esküvők", text: "Személyre szabott menüsor, ünnepi környezet és teljes vendéglátás az első egyeztetéstől a nagy napig.", cta: "Esküvői ajánlatot kérek" },
  { number: "05", title: "Catering", text: "Helyben vagy külső helyszínen: az ételeket, a kiszolgálást és a biztos vendéglátói hátteret is adjuk.", cta: "Catering ajánlatot kérek" },
];

const weeklyMenu = [["Hétfő", "Leves és kétféle főétel"], ["Kedd", "Leves és kétféle főétel"], ["Szerda", "Leves és kétféle főétel"], ["Csütörtök", "Leves és kétféle főétel"], ["Péntek", "Leves és kétféle főétel"]];

function BrandMark({ inverse = false }: { inverse?: boolean }) {
  return <span className={`brand-mark ${inverse ? "brand-mark--inverse" : ""}`} aria-hidden="true"><svg viewBox="0 0 64 64" role="img"><circle cx="32" cy="32" r="31" fill="#D3B25D" /><path d="M11 43C22 37 33 30 41 5h17v19C43 26 32 35 24 55H11V43Z" fill="#E62030" /><path d="M17 49c10-2 17-1 23 2M21 46c7-9 13-19 17-34M16 39c9-4 16-9 22-17" fill="none" stroke="#fff" strokeWidth="4.2" strokeLinecap="round" /></svg></span>;
}

export default function Home() {
  return (
    <main id="top">
      <div className="announcement"><div className="shell announcement__inner"><span>Várpalota · a Zichy-kastély szomszédságában</span><a href="tel:+36302644081">Asztalfoglalás: +36 30 264 4081</a></div></div>
      <header className="site-header"><div className="shell header__inner">
        <a className="brand" href="#top" aria-label="Kastélydomb Kávézó és Étterem"><BrandMark /><span className="brand__word"><b>kastélydomb</b><small>Kávézó és Étterem</small></span></a>
        <nav className="desktop-nav" aria-label="Fő navigáció"><a href="#kinalat">Kínálat</a><a href="#szolgaltatasok">Szolgáltatások</a><a href="#esemenyek">Események</a><a href="#rolunk">Rólunk</a></nav>
        <a className="header-cta" href="#kapcsolat">Kapcsolat <span>↗</span></a>
        <details className="mobile-nav"><summary aria-label="Menü megnyitása"><span></span><span></span></summary><nav aria-label="Mobil navigáció"><a href="#kinalat">Kínálat</a><a href="#szolgaltatasok">Szolgáltatások</a><a href="#esemenyek">Események</a><a href="#rolunk">Rólunk</a><a href="#kapcsolat">Kapcsolat</a></nav></details>
      </div></header>

      <section className="hero">
        <div className="hero__image"><Image src="/images/wolt-borito.webp" alt="A Kastélydomb étterem kínálatából: pizzák és frissen készült fogások" fill priority sizes="(max-width: 900px) 100vw, 54vw" /><span className="hero__image-label">Saját kínálatunkból</span></div>
        <div className="hero__content"><p className="kicker">Étterem · rendezvény · catering</p><h1>Jó ízek.<br /><em>Jó alkalmak.</em><br />Jó helyen.</h1><p className="hero__lead">Hétköznapi ebédek, ráérős vacsorák és emlékezetes események Várpalota egyik különleges pontján.</p><div className="button-row"><a className="button button--red" href="#kinalat">Heti menü <span>↓</span></a><a className="button button--outline" href="#kapcsolat">Asztalt foglalok</a></div><div className="hero__facts"><div><span>01</span><b>À la carte és heti menü</b></div><div><span>02</span><b>150 fős rendezvényhelyszín</b></div></div></div>
      </section>

      <section className="quick-info" aria-label="Gyors információk"><div className="shell quick-info__grid"><div><span>Cím</span><b>8100 Várpalota, Mandulás lakótelep 2.</b></div><div><span>Telefon</span><a href="tel:+36302644081">+36 30 264 4081</a></div><div><span>Rendelés</span><a href="https://kastelydomb.etteremwebshop.hu" target="_blank" rel="noreferrer">Online webshop ↗</a></div><div><span>Aktuális hírek</span><a href="https://www.facebook.com/Kastelydombkavezo" target="_blank" rel="noreferrer">Facebook oldal ↗</a></div></div></section>

      <section className="intro section" id="rolunk"><div className="shell intro__grid"><div className="section-index">01 — KASTÉLYDOMB</div><div><h2>Több mint egy étterem.<br /><em>Egy hely az együttléthez.</em></h2></div><div className="intro__image image-frame"><Image src="/images/etterem-belso.webp" alt="A Kastélydomb Kávézó és Étterem megújult belső tere" fill sizes="(max-width: 850px) 100vw, 43vw" /></div><div className="intro__copy"><p className="lead-copy">A városközponthoz közel, a Zichy-kastély és a történelmi templom szomszédságában várunk.</p><p>Könnyen megközelíthető helyszín, ingyenes parkolás és személyes vendéglátás. Legyen szó egy gyors ebédről, családi ünnepről vagy több száz részletből összeálló esküvőről, nálunk minden alkalom ugyanazzal a figyelemmel kezdődik.</p><div className="signature">Kastélydombi vendéglátás</div></div></div></section>

      <section className="menu section" id="kinalat"><div className="shell"><div className="section-head section-head--light"><div><div className="section-index">02 — KÍNÁLAT</div><h2>Heti menü,<br /><em>mindig frissen.</em></h2></div><p>Az éles oldalon ez a blokk hetente frissíthető: egy helyen látszik a teljes heti kínálat, az ár és a rendelési információ.</p></div><div className="menu__layout"><div className="week-card"><div className="week-card__head"><div><span>Aktuális hét</span><h3>Ebédmenü</h3></div><b>Hétfő–péntek</b></div><div className="week-list">{weeklyMenu.map(([day, meal]) => <div className="week-row" key={day}><strong>{day}</strong><span>{meal}<small>Az aktuális fogások feltöltésre várnak</small></span><i>A / B / C</i></div>)}</div><p className="draft-note">Tervezeti állapot: publikálás előtt az aktuális heti fogások és árak kerülnek ide.</p></div><aside className="menu-links"><div className="menu-links__top"><BrandMark inverse /><span>Válassz kedved és alkalmad szerint.</span></div><div><a href="https://kastelydombkavezo.hu/etlap/" target="_blank" rel="noreferrer"><span><small>Teljes kínálat</small>Étlap</span><b>↗</b></a><a href="https://kastelydombkavezo.hu/etteremrol/italok/" target="_blank" rel="noreferrer"><span><small>Frissítők és italok</small>Itallap</span><b>↗</b></a><a href="https://kastelydomb.etteremwebshop.hu" target="_blank" rel="noreferrer"><span><small>Átvétel vagy kiszállítás</small>Online rendelés</span><b>↗</b></a></div></aside></div></div></section>

      <section className="services section" id="szolgaltatasok"><div className="shell"><div className="section-head"><div><div className="section-index">03 — SZOLGÁLTATÁSOK</div><h2>Minden alkalomhoz<br /><em>van egy jó megoldásunk.</em></h2></div><p>A szolgáltatások külön céloldalakat kapnak majd, így mindegyik önálló kampánnyal és pontos ajánlattal értékesíthető.</p></div><div className="services__grid">{services.map((service) => <article className="service-card" key={service.number}><span className="service-card__number">{service.number}</span><div><h3>{service.title}</h3><p>{service.text}</p></div><a href="#kapcsolat">{service.cta}<span>↗</span></a></article>)}</div></div></section>

      <section className="events section" id="esemenyek"><div className="shell"><div className="section-head"><div><div className="section-index">04 — ESEMÉNYEK</div><h2>Programok,<br /><em>amik összehoznak.</em></h2></div><p>Tematikus vacsorák, zenés estek és ünnepi programok. A következő esemény mindig kiemelt helyet kap.</p></div><div className="event-feature"><div className="event-feature__image image-frame"><Image src="/images/etterem-03.webp" alt="Ünnepi teríték a Kastélydomb éttermében" fill sizes="(max-width: 850px) 100vw, 56vw" /></div><div className="event-feature__copy"><span className="event-pill">Következő esemény</span><h3>Az új program hamarosan érkezik</h3><p>Itt jelenik meg az esemény időpontja, rövid leírása, ára és a foglalás vagy jegyvásárlás lehetősége.</p><a className="text-link" href="https://www.facebook.com/Kastelydombkavezo" target="_blank" rel="noreferrer">Aktuális hírek a Facebookon <span>↗</span></a></div></div></div></section>

      <section className="wedding"><div className="wedding__image"><Image src="/images/etterem-08.webp" alt="Esküvői teríték a Kastélydomb rendezvénytermében" fill sizes="100vw" /></div><div className="shell wedding__content"><p className="kicker">Esküvő a Kastélydombon</p><h2>A nagy naphoz<br /><em>méltó figyelemmel.</em></h2><p>Helyszín, menüsor és vendéglátás egy kézben — hogy ti valóban az ünnepre figyelhessetek.</p><a className="button button--sand" href="#kapcsolat">Esküvői ajánlatot kérek <span>↗</span></a></div></section>

      <section className="contact section" id="kapcsolat"><div className="shell contact__grid"><div className="contact__intro"><div className="section-index">05 — KAPCSOLAT</div><h2>Beszéljük meg<br /><em>az alkalmat.</em></h2><p>Asztalfoglalás, rendezvény, esküvő, közétkeztetés vagy catering? Írd meg röviden, miben segíthetünk.</p><div className="contact__details"><a href="tel:+36302644081"><small>Mobil</small>+36 30 264 4081</a><a href="tel:+3688470350"><small>Telefon</small>+36 88 470 350</a><a href="mailto:fenyocsaba@gmail.com"><small>E-mail</small>fenyocsaba@gmail.com</a><span><small>Cím</small>8100 Várpalota, Mandulás lakótelep 2.</span></div></div><ContactForm /></div></section>

      <footer className="footer"><div className="shell footer__top"><a className="brand brand--footer" href="#top"><BrandMark inverse /><span className="brand__word"><b>kastélydomb</b><small>Kávézó és Étterem</small></span></a><div className="footer__links"><a href="https://www.facebook.com/Kastelydombkavezo" target="_blank" rel="noreferrer">Facebook</a><a href="https://kastelydomb.etteremwebshop.hu" target="_blank" rel="noreferrer">Online rendelés</a><a href="#top">Vissza az elejére ↑</a></div></div><div className="shell footer__bottom"><span>© 2026 Kastélydomb Kávézó és Étterem</span><span>Várpalota</span></div></footer>
    </main>
  );
}
